keys:
  - &admin_lisa age12pj207m3u8f5ql70rccf8pm9h4xuhcgeec94gfnum7583ys9dv2qwc38tv
  - &server_root age15q57cpasm2twuu45x6g3e0dge9k9xawy7mjc7lnzwlxu78pfcd6qfzkwze
  - &local_machine age1t0up4r7qszg9c296864a626hzt0nepkrgwfywhlcsh3aapyyqcvqzxe6m0

creation_rules:
  - path_regex: secrets/auto-sync-update\.env$
    key_groups:
      - age:
          - *admin_lisa
          - *server_root
          - *local_machine
  - path_regex: secrets/vaultwarden.*\.(env|json)$
    key_groups:
      - age:
          - *admin_lisa
          - *server_root
          - *local_machine
  - path_regex: secrets/.*\.yaml$
    encrypted_regex: ^(data|stringData|sops|age_keys)$
    key_groups:
      - age:
          - *admin_lisa
          - *local_machine
  - path_regex: secrets/[^/]+\.(env|ini|json|e)$
    key_groups:
      - age:
          - *admin_lisa
          - *server_root
