# DO-NOT-EDIT: Generated by github:vic/flake-file.
# To re-generate use: nix-shell . -A flake-file.sh --run write-inputs
{
  codex-cli-nix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:sadjow/codex-cli-nix";
  };
  disko = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/disko";
  };
  flake-file.url = "github:denful/flake-file";
  flake-parts.url = "https://flakehub.com/f/hercules-ci/flake-parts/0.1.*";
  home-manager = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:nix-community/home-manager";
  };
  homebrew-cask = {
    flake = false;
    url = "github:homebrew/homebrew-cask";
  };
  homebrew-core = {
    flake = false;
    url = "github:homebrew/homebrew-core";
  };
  import-tree = {
    flake = false;
    url = "github:vic/import-tree";
  };
  nix-darwin = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "https://flakehub.com/f/nix-darwin/nix-darwin/0.1.*";
  };
  nix-homebrew.url = "github:zhaofengli/nix-homebrew";
  nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1";
  onepassword-shell-plugins = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:1Password/shell-plugins";
  };
  shop-empty-track = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:LisaScheers/shop-empty-track/main";
  };
  sops-nix = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "https://flakehub.com/f/Mic92/sops-nix/0.1.*";
  };
  stock-keeper = {
    inputs.nixpkgs.follows = "nixpkgs";
    url = "github:LisaScheers/stock-keeper/main";
  };
  systems.url = "github:nix-systems/default";
}
